# encoding: utf-8
module Bucks
  class Currency
    CURRENCIES = {
      "Afghanistan" => :AFN, 
      "Aland Islands" => :EUR,
      "Albania" => :ALL, 
      "Algeria" => :DZD, 
      "United States" => :USD, 
      "American Samoa" => :USD, 
      "American Virgin Islands" => :USD, 
      "Andorra" => :EUR, 
      "Angola" => :AOA, 
      "Anguilla" => :XCD, 
      "Antarctica" => :USD,
      "Antigua And Barbuda" => :XCD, 
      "Argentina" => :ARS, 
      "Armenia" => :AMD, 
      "Aruba" => :AWG, 
      "Australia" => :AUD, 
      "Austria" => :EUR, 
      "Azerbaijan" => :AZN, 
      "Azores" => :EUR, 
      "Bahamas" => :BSD, 
      "Bahrain" => :BHD, 
      "Baleares (Balearic Islands)" => :EUR, 
      "Bangladesh" => :BDT, 
      "Barbados" => :BBD, 
      "Barbuda and Antigua" => :XCD, 
      "Belarus" => :BYR, 
      "Belgium" => :EUR, 
      "Belize" => :BZD, 
      "Benin" => :XOF, 
      "Bermuda" => :BMD, 
      "Bhutan" => :BTN, 
      "Bhutan" => :INR, 
      "Bolivia" => :BOB, 
      "Bonaire" => :ANG, 
      "Bosnia and Herzegovina" => :BAM, 
      "Botswana" => :BWP, 
      "Bouvet Island" => :NOK, 
      "Brazil" => :BRL, 
      "Britain (United Kingdom)" => :GBP, 
      "British Indian Ocean Territory" => :USD, 
      "British Virgin Islands" => :USD, 
      "Brunei Darussalam" => :BND, 
      "Bulgaria" => :BGN, 
      "Burkina Faso" => :XOF, 
      "Burma (Myanmar)" => :MMK, 
      "Burundi" => :BIF, 
      "Cote d'Ivoire" => :XOF, 
      "Caicos and Turks Islands" => :USD, 
      "Cambodia" => :KHR, 
      "Cameroon" => :XAF, 
      "Canada" => :CAD, 
      "Canary Islands" => :EUR, 
      "Cape Verde" => :CVE, 
      "Cayman Islands" => :KYD, 
      "Central African Republic" => :XAF, 
      "Chad" => :XAF, 
      "Chile" => :CLP, 
      "China" => :CNY, 
      "Christmas Island" => :AUD, 
      "Cocos (Keeling) Islands" => :AUD, 
      "Colombia" => :COP, 
      "Communauté Financière Africaine (CFA)" => :XAF, 
      "Comoros" => :KMF, 
      "Comptoirs Français du Pacifique (CFP)" => :XPF, 
      "Congo" => :XAF, 
      "Congo, the Democratic Republic of the" => :CDF, 
      "Cook Islands" => :NZD, 
      "Costa Rica" => :CRC, 
      "Croatia" => :HRK, 
      "Cuba" => :CUP, 
      "Curaço" => :ANG, 
      "Cyprus" => :EUR, 
      "Cyprus" => :CYP, 
      "Czech Republic" => :CZK, 
      "Denmark" => :DKK, 
      "Djibouti" => :DJF, 
      "Dominica" => :XCD, 
      "Dominican Republic" => :DOP, 
      "Dutch (Netherlands)" => :EUR, 
      "East Timor" => :IDR, 
      "Ecuador" => :USD, 
      "Egypt" => :EGP, 
      "Ireland" => :EUR, 
      "El Salvador" => :SVC, 
      "El Salvador" => :USD, 
      "England (United Kingdom)" => :GBP, 
      "Equatorial Guinea" => :XAF, 
      "Eritrea" => :ETB, 
      "Eritrea" => :ERN, 
      "Estonia" => :EEK, 
      "Ethiopia" => :ETB, 
      "Euro Member Countries" => :EUR, 
      "Falkland Islands (Malvinas)" => :FKP, 
      "Faroe Islands" => :DKK, 
      "Fiji" => :FJD, 
      "Finland" => :EUR, 
      "France" => :EUR, 
      "French Guiana" => :EUR, 
      "French Pacific Islands" => :XPF, 
      "French Polynesia" => :XPF, 
      "French Southern Territories" => :EUR, 
      "Futuna and Wallis Islands" => :XPF, 
      "Gabon" => :XAF, 
      "Gambia" => :GMD, 
      "Georgia" => :GEL, 
      "Germany" => :EUR, 
      "Ghana" => :GHS, 
      "Gibraltar" => :GIP, 
      "Gold" => :XAU, 
      "Great Britain (United Kingdom)" => :GBP, 
      "Greece" => :EUR, 
      "Greenland" => :DKK, 
      "Grenada" => :XCD, 
      "Saint Vincent and the Grenadines" => :XCD, 
      "Guadeloupe" => :EUR, 
      "Guam" => :USD, 
      "Guatemala" => :GTQ, 
      "Guernsey" => :GGP, 
      "Guinea" => :GNF, 
      "Guinea-Bissau" => :XOF, 
      "Guyana" => :GYD, 
      "Haiti" => :HTG, 
      "Haiti" => :USD, 
      "Heard Island and McDonald Islands" => :AUD, 
      "Bosnia and Herzegowina" => :BAM, 
      "Holland (Netherlands)" => :EUR, 
      "Holy See (Vatican City State)" => :EUR, 
      "Honduras" => :HNL, 
      "Hong Kong" => :HKD, 
      "Hungary" => :HUF, 
      "Iceland" => :ISK, 
      "India" => :INR, 
      "Indonesia" => :IDR, 
      "International Monetary Fund (IMF)" => :XDR, 
      "Iran, Islamic Republic of" => :IRR, 
      "Iraq" => :IQD, 
      "Ireland (Eire)" => :EUR, 
      "Isle of Man" => :IMP, 
      "Israel" => :ILS, 
      "Italy" => :EUR, 
      "Jamaica" => :JMD, 
      "Jan Mayen and Svalbard" => :NOK, 
      "Japan" => :JPY, 
      "Jersey" => :JEP, 
      "Jordan" => :JOD, 
      "Kazakhstan" => :KZT, 
      "Keeling (Cocos) Islands" => :AUD, 
      "Kenya" => :KES, 
      "Kiribati" => :AUD, 
      "Korea, Democratic People's Republic of" => :KPW, 
      "Korea, Republic of" => :KRW, 
      "Kuwait" => :KWD, 
      "Kyrgyzstan" => :KGS, 
      "Lao People's Democratic Republic" => :LAK, 
      "Latvia" => :LVL, 
      "Lebanon" => :LBP, 
      "Lesotho" => :LSL, 
      "Lesotho" => :ZAR, 
      "Liberia" => :LRD, 
      "Libya" => :LYD,
      "Libyan Arab Jamahiriya" => :LYD,
      "Liechtenstein" => :CHF, 
      "Lithuania" => :LTL, 
      "Luxembourg" => :EUR, 
      "Macao" => :MOP, 
      "Macedonia, The Former Yugoslav Republic Of" => :MKD, 
      "Madagascar" => :MGA, 
      "Madeira Islands" => :EUR, 
      "Malawi" => :MWK, 
      "Malaysia" => :MYR, 
      "Maldives" => :MVR, 
      "Mali" => :XOF, 
      "Malta" => :EUR,  
      "Malvinas (Falkland Islands)" => :FKP, 
      "Mariana Islands (Northern)" => :USD, 
      "Marshall Islands" => :USD, 
      "Martinique" => :EUR, 
      "Mauritania" => :MRO, 
      "Mauritius" => :MUR, 
      "Mayotte" => :EUR, 
      "Heard and McDonald Islands" => :AUD, 
      "Mexico" => :MXN, 
      "Micronesia, Federated States of" => :USD, 
      "Midway Islands" => :USD, 
      "Miquelon and Saint Pierre" => :EUR, 
      "Moldova, Republic of" => :MDL, 
      "Monaco" => :EUR, 
      "Mongolia" => :MNT, 
      "Montenegro" => :EUR, 
      "Montserrat" => :XCD, 
      "Morocco" => :MAD, 
      "Mozambique" => :MZN, 
      "Myanmar" => :MMK, 
      "Namibia" => :NAD, 
      "Namibia" => :ZAR, 
      "Nauru" => :AUD, 
      "Nepal" => :NPR, 
      "Netherlands Antilles" => :ANG, 
      "Netherlands" => :EUR, 
      "Nevis and Saint Kitts" => :XCD, 
      "New Caledonia" => :XPF, 
      "New Zealand" => :NZD, 
      "Nicaragua" => :NIO, 
      "Niger" => :XOF, 
      "Nigeria" => :NGN, 
      "Niue" => :NZD, 
      "Norfolk Island" => :AUD, 
      "Northern Mariana Islands" => :USD, 
      "Norway" => :NOK, 
      "Oman" => :OMR, 
      "Pakistan" => :PKR, 
      "Palau" => :USD, 
      "Palestinian Territory, Occupied" => :NIS,
      "Palladium" => :XPD, 
      "Panama" => :PAB, 
      "Panama" => :USD, 
      "Papua New Guinea" => :PGK, 
      "Paraguay" => :PYG, 
      "Peru" => :PEN, 
      "Philippines" => :PHP, 
      "Pitcairn" => :NZD, 
      "Platinum" => :XPT, 
      "Poland" => :PLN, 
      "Portugal" => :EUR, 
      "Sao Tome and Principe" => :STD, 
      "Puerto Rico" => :USD, 
      "Qatar" => :QAR, 
      "Reunion" => :EUR, 
      "Romania" => :RON, 
      "Russian Federation" => :RUB, 
      "Rwanda" => :RWF, 
      "São Tome and Principe" => :STD, 
      "Saba" => :ANG, 
      "Sahara (Western)" => :MAD, 
      "Saint Barthelemy" => :EUR,
      "Saint Christopher" => :XCD, 
      "Saint Helena" => :SHP, 
      "Saint Kitts and Nevis" => :XCD, 
      "Saint Lucia" => :XCD, 
      "Saint Pierre and Miquelon" => :EUR, 
      "Saint Vincent and The Grenadines" => :XCD, 
      "Saint-Martin" => :EUR, 
      "Samoa (American)" => :USD, 
      "Samoa" => :WST, 
      "San Marino" => :EUR, 
      "Saudi Arabia" => :SAR, 
      "Seborga" => :SPL, 
      "Senegal" => :XOF, 
      "Serbia" => :RSD, 
      "Seychelles" => :SCR, 
      "Sierra Leone" => :SLL, 
      "Silver" => :XAG, 
      "Singapore" => :SGD, 
      "Sint Eustatius" => :ANG, 
      "Sint Maarten" => :ANG, 
      "Slovakia" => :EUR, 
      "Slovenia" => :EUR, 
      "Solomon Islands" => :SBD, 
      "Somalia" => :SOS, 
      "South Africa" => :ZAR, 
      "South Georgia and the South Sandwich Islands" => :GBP, 
      "Spain" => :EUR, 
      "Sri Lanka" => :LKR, 
      "Sudan" => :SDG, 
      "Suriname" => :SRD, 
      "Svalbard and Jan Mayen" => :NOK, 
      "Swaziland" => :SZL, 
      "Sweden" => :SEK, 
      "Switzerland" => :CHF, 
      "Syria" => :SYP, 
      "Syrian Arab Republic" => :SYP,
      "Taiwan, Province of China" => :TWD, 
      "Tajikistan" => :RUB, 
      "Tajikistan" => :TJS, 
      "Tanzania, United Republic of" => :TZS, 
      "Thailand" => :THB, 
      "Timor-Leste" => :IDR, 
      "Tobago and Trinidad" => :TTD, 
      "Togo" => :XOF, 
      "Tokelau" => :NZD, 
      "Tonga" => :TOP, 
      "Trinidad and Tobago" => :TTD, 
      "Tunisia" => :TND, 
      "Turkey" => :TRY, 
      "Turkmenistan" => :TMM, 
      "Turks and Caicos Islands" => :USD, 
      "Tuvalu" => :TVD, 
      "Uganda" => :UGX, 
      "Ukraine" => :UAH, 
      "United Arab Emirates" => :AED, 
      "United Kingdom" => :GBP, 
      "United States Minor Outlying Islands" => :USD, 
      "United States of America" => :USD, 
      "Uruguay" => :UYU, 
      "US Virgin Islands" => :USD, 
      "Uzbekistan" => :UZS, 
      "Vanuatu" => :VUV, 
      "Vatican City (The Holy See)" => :EUR, 
      "Venezuela" => :VEB, 
      "Venezuela" => :VEF, 
      "Viet Nam" => :VND, 
      "Virgin Islands, U.S." => :USD, 
      "Virgin Islands, British" => :USD, 
      "Wake Island" => :USD, 
      "Wallis and Futuna" => :XPF, 
      "Western Sahara" => :MAD, 
      "Yemen" => :YER, 
      "Zambia" => :ZMK, 
      "Zimbabwe" => :ZWD, 
    }

    COUNTRIES = ["Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
      "Anguilla", "Antarctica", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria",
      "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
      "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil",
      "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
      "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
      "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo",
      "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
      "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
      "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)",
      "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
      "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
      "Guinea-Bissau", "Guyana", "Haiti", "Heard and McDonald Islands", "Holy See (Vatican City State)",
      "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of", "Iraq",
      "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
      "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan",
      "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya",
      "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic Of",
      "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
      "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of",
      "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
      "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
      "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau",
      "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
      "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation",
      "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia",
      "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
      "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
      "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
      "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname",
      "Svalbard and Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
      "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste",
      "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
      "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
      "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
      "Viet Nam", "Virgin Islands, British", "Virgin Islands, U.S.", "Wallis and Futuna", "Western Sahara",
      "Yemen", "Zambia", "Zimbabwe"
    ]    
  
    def self.find(country)
      CURRENCIES[country]
    end
  end
end

